### ISSUE TITLE
[stable/concourse] Concourse's pre-start statefulset cleaning doesn't work properly

### ISSUE THREAD

**Issue by emempi** [concourse/charts#6]
**Describe the bug**

https://github.com/concourse/charts/blob/master/stable/concourse/templates/worker-statefulset.yaml#L64

The initContainer that's supposed to clean up concourse's workdir before starting has a shellscript bug that prevents it from actually deleting the data. This is due to the way shell does globbing; particularly:

```
rm -rf "{{ .Values.concourse.worker.workDir }}/*"
```

gets expanded into:

```
rm -rf "/concourse-work-dir/*"
```

which then fails due to the non-existent path `/concourse-work-dir/*`.

**Version of Helm and Kubernetes**:
Helm 2.14.1, Kubernetes 1.13.

**Which chart**:
stable/concourse

**What happened**:
Concourse didn't clean up its workdir directory after re-creating the pods.

**What you expected to happen**:
According to the initContainer, Concourse should clean up its workdir.

**How to reproduce it** (as minimally and precisely as possible):
Restart concourse pod with non-empty workdir.

**Anything else we need to know**:

**Comment by emempi** [comment]
@cirocosta apologies for pinging directly, but looks like bugs/PRs often go stale here and no reviewers are being assigned automatically. Is that intentional?

**Comment by cirocosta** [comment]
Hi @emempi ,

Sorry for the super long wait! We were allocating less time to the Chart itself these weeks, but we're back! 😁  

Thanks for submitting the issue and the corresponding PR - good catch! That's indeed problematic 😅 

Although we have this repo (concourse/charts) which we use for pre-releases, we'll be very soon moving to https://github.com/concourse/helm, which contains just the Concourse chart and nothing else. That way we'll be able to also backport fixes when necessary, and have our continuous integration, etc all set up.

While we're not yet finished with having `concourse/helm` ready, would you mind submitting the PR against `helm/charts` directly? This way we'll be able to get it merged in.

Thank you!

**Comment by emempi** [comment]
Sure :-) One fresh PR ready at https://github.com/helm/charts/pull/17920 .

**Comment by cirocosta** [comment]
thank you very much, @emempi ! 😁
